"""Self-contained Swagger UI HTML export.

Builds a single, dependency-free HTML page with:
  - Swagger UI CSS + JS inlined (vendored from ``vendor/swagger-ui-dist``),
  - the OpenAPI spec embedded inline (as JSON in a <script> tag),
  - an inline favicon (configurable via ``--icon``).

Opening the produced file makes zero network requests: no CDN scripts, no
external fonts, no favicon fetch. The same shell is reused by ``serve.py``.
"""

import base64
import json
import mimetypes
import os

VENDOR_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "vendor",
    "swagger-ui-dist",
)
SWAGGER_UI_CSS = os.path.join(VENDOR_DIR, "swagger-ui.css")
SWAGGER_UI_BUNDLE = os.path.join(VENDOR_DIR, "swagger-ui-bundle.js")

DEFAULT_FAVICON = (
    "data:image/svg+xml,"
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E"
    "%3Crect width='32' height='32' rx='6' fill='%2363a64f'/%3E"
    "%3Ctext x='16' y='22' font-size='16' font-family='sans-serif' "
    "font-weight='bold' fill='white' text-anchor='middle'%3EAP%3C/text%3E%3C/svg%3E"
)


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def embed_spec(spec):
    """JSON-serialize a spec so it is safe inside a <script> tag."""
    return json.dumps(spec, indent=2).replace("</", "<\\/")


def embed_icon(path):
    """Read an image file and return it as a base64 data: URI."""
    mime = mimetypes.guess_type(path)[0] or "image/png"
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return "data:{};base64,{}".format(mime, b64)


def build_standalone_html(spec, title=None, icon=None, generated_at=None):
    """Build the fully self-contained HTML page for ``spec``.

    Args:
        spec: OpenAPI dict (or JSON string) to embed.
        title: Page title override; defaults to the spec's ``info.title``.
        icon: Path to a favicon image, or None for the built-in inline icon.
        generated_at: Human-readable timestamp string to embed, or None.

    Returns:
        The complete HTML page as a string. It references no external URLs.
    """
    if isinstance(spec, str):
        spec = json.loads(spec)
    info_title = ""
    if isinstance(spec, dict):
        info_title = (spec.get("info") or {}).get("title") or ""
    page_title = title or info_title or "API Documentation"

    icon_uri = embed_icon(icon) if icon else DEFAULT_FAVICON
    spec_json = embed_spec(spec)
    generated_comment = ""
    if generated_at:
        generated_comment = (
            "<!-- Generated by apidocgen on {} -->\n    ".format(generated_at)
        )

    return _HTML_SHELL.format(
        title=page_title,
        favicon=icon_uri,
        generated_comment=generated_comment,
        swagger_css=_read(SWAGGER_UI_CSS),
        swagger_bundle=_read(SWAGGER_UI_BUNDLE),
        spec_json=spec_json,
    )


_HTML_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
    <link rel="icon" href="{favicon}">
    {generated_comment}<style>
{swagger_css}
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script id="api-spec" type="application/json">{spec_json}</script>
    <script>
{swagger_bundle}
    </script>
    <script>
        window.onload = function () {{
            var spec = JSON.parse(document.getElementById('api-spec').textContent);
            window.ui = SwaggerUIBundle({{
                spec: spec,
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIBundle.SwaggerUIStandalonePreset
                ],
                layout: 'StandaloneLayout'
            }});
        }};
    </script>
</body>
</html>
"""