"""Tests for Issue #6: self-contained interactive HTML export (offline Swagger UI).

Covers: vendored swagger-ui assets present, assets inlined into the single
file, zero external network references, spec embedded inline (with examples
preserved), favicon + timestamp + title overrides, and escaping of the spec.
"""

import json
import os
import tempfile
import unittest

from generator import html as html_mod
from generator.html import build_standalone_html

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SAMPLE_SPEC = {
    "openapi": "3.0.3",
    "info": {"title": "Demo API", "version": "1.0.0"},
    "paths": {
        "/users": {
            "get": {
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {"type": "array", "items": {"type": "object"}},
                                "example": [{"id": 1, "name": "John Doe"}],
                            }
                        },
                    }
                },
            }
        }
    },
}


class VendoredAssetsTests(unittest.TestCase):
    def test_swagger_ui_assets_vendored(self):
        for name in ("swagger-ui-bundle.js", "swagger-ui.css"):
            path = os.path.join(html_mod.VENDOR_DIR, name)
            self.assertTrue(os.path.exists(path), f"missing vendored asset {name}")
            self.assertGreater(os.path.getsize(path), 50_000, f"{name} looks empty")


class StandaloneHTMLTests(unittest.TestCase):
    def test_body_sections_present(self):
        html = build_standalone_html(SAMPLE_SPEC, title="My Title")
        self.assertIn("<title>My Title</title>", html)
        self.assertIn(".swagger-ui{color:", html)  # css bundle marker
        self.assertIn("SwaggerUIBundle", html)  # js bundle marker
        self.assertIn('id="api-spec"', html)

    def test_no_external_network_references(self):
        """Acceptance: zero network requests - no CDN, no off-host fonts."""
        html = build_standalone_html(SAMPLE_SPEC, title="T")
        self.assertNotIn('src="http', html)
        self.assertNotIn('href="http', html)
        self.assertNotIn("url(http", html)  # no external css url()
        self.assertNotIn("@import", html)
        self.assertNotIn("unpkg.com", html)
        self.assertNotIn("cdn.jsdelivr", html)
        for link in html.split("<link")[1:]:
            href = link.split(">", 1)[0]
            self.assertTrue(href.startswith(' rel="icon" href="data:'),
                            f"non-inline <link>: {href!r}")

    def test_favicon_is_inline_data_uri(self):
        html = build_standalone_html(SAMPLE_SPEC, title="T")
        self.assertIn('rel="icon" href="data:', html)

    def test_spec_embedded_inline_and_parseable(self):
        html = build_standalone_html(SAMPLE_SPEC, title="T")
        start = html.index('<script id="api-spec" type="application/json">')
        raw_json = html[start + len('<script id="api-spec" type="application/json">'):]
        raw_json = raw_json[: raw_json.index("</script>")]
        embedded = json.loads(raw_json)
        self.assertEqual(embedded, SAMPLE_SPEC)

    def test_examples_preserved_in_embedding(self):
        """Acceptance: request/response examples stay viewable in the artifact."""
        html = build_standalone_html(SAMPLE_SPEC, title="T")
        self.assertIn("John Doe", html)
        self.assertIn('"example"', html)

    def test_title_override_wins_over_spec_info(self):
        html = build_standalone_html(SAMPLE_SPEC, title="Override")
        self.assertIn("<title>Override</title>", html)

    def test_title_falls_back_to_spec_info(self):
        html = build_standalone_html(SAMPLE_SPEC)
        self.assertIn("<title>Demo API</title>", html)

    def test_generated_at_timestamp_embedded(self):
        html = build_standalone_html(SAMPLE_SPEC, generated_at="2026-01-02 03:04:05")
        self.assertIn("Generated by apidocgen on 2026-01-02 03:04:05", html)

    def test_no_timestamp_by_default(self):
        html = build_standalone_html(SAMPLE_SPEC)
        self.assertNotIn("Generated by apidocgen", html)

    def test_icon_file_embedded_as_data_uri(self):
        with tempfile.TemporaryDirectory() as d:
            icon = os.path.join(d, "favicon.png")
            with open(icon, "wb") as f:
                f.write(b"\x89PNG\r\n\x1a\nfakepngdata")
            html = build_standalone_html(SAMPLE_SPEC, title="T", icon=icon)
        self.assertIn('rel="icon" href="data:image/png;base64,', html)

    def test_spec_closing_script_tags_are_escaped(self):
        nasty = json.loads(json.dumps(SAMPLE_SPEC))
        nasty["info"]["description"] = "x</script><script>alert(1)</script>y"
        html = build_standalone_html(nasty, title="T")
        self.assertIn("<\\/script>", html)
        self.assertNotIn("x</script>", html)

    def test_accepts_json_string_spec(self):
        html = build_standalone_html(json.dumps(SAMPLE_SPEC), title="T")
        self.assertIn("<title>T</title>", html)


if __name__ == "__main__":
    unittest.main()